FROM alpine

RUN apk update && apk upgrade
RUN apk add openjdk8-dbg

# install jemalloc
WORKDIR /opt/debug
RUN apk add build-base
RUN apk add graphviz
RUN wget https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2
RUN tar -xvf jemalloc-5.3.0.tar.bz2
WORKDIR /opt/debug/jemalloc-5.3.0
RUN ./configure --enable-prof
RUN make
RUN make install
ENV LD_PRELOAD=/usr/local/lib/libjemalloc.so.2
ENV MALLOC_CONF="prof:true,prof_leak:true,lg_prof_interval:30,lg_prof_sample:30"
